# 指定了执行脚本的分支。
branches:
  only:
  #  - master
  - maintenance
# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
  - node_modules

# 指定博客的仓库地址
env:
  global:
  - GH_REF: github.com/bobit/bobit.github.io.git

#travis-ci生成静态文件，并将public目录下的文件全部 push 到你所指定仓库的 master 分支上去。
# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
- cd ./source
- git init
- git add .
- git commit -m "Automatically Update !"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# End: Build LifeCycle